### PR TITLE
Remove star import in jmetal.lab.statistical_test.functions

### PR DESCRIPTION
**Pull request by rnestler**
This helps with statical analysis tools like mypy or flake8.

### CODE REVIEW

**Comment by rnestler** [comment]
Ah I just noticed that this project uses git-flow workflow with develop as the development branch. I'll rebase this on develop and change the target branch.

Is there any reason that `develop` isn't the default branch? This would help a lot when contributing first to the project, since it will be visible directly that development should happen there.

**Comment by rnestler** [comment]
@benhid What was the reason to close this?

**Comment by benhid** [comment]
Sorry, @rnestler, reopening now. 👍

**Comment by rnestler** [comment]
I rebased to the latest develop.

**Comment by rnestler** [comment]
@benhid What is the status on this?

**Comment by rnestler** [comment]
@ajnebro Care to take a look at this as well?

**Pull request merged**
