### PR TITLE
Rename master to main in contributing docs

### PR DESCRIPTION
**Pull request by rnestler**
What is the reason for the duplicated documents? I just fixed the branch name in both of them, but I'm still wondering why.

### CODE REVIEW

**Comment by rnestler** [comment]
@benhid What was the reason to close this?

**Comment by benhid** [comment]
Sorry, @rnestler,

I accidentally deleted the develop branch, and as a result, the pull request was automatically closed. 

Reopening PR!

**Comment by rnestler** [comment]
> I accidentally deleted the develop branch, and as a result, the pull request was automatically closed.

Alright. Is there a reason to use the develop branch as an intermediate for developing instead of just using the main branch? Since `main` is set as the default branch on GitHub this is quite confusing for contributors, since PRs will be opened against main by default.

**Comment by rnestler** [comment]
@benhid What is the status on this?

**Comment by rnestler** [comment]
@benhid What is the status on this?

**Comment by rnestler** [comment]
@ajnebro Care to take a look at this as well?

**Pull request merged**
